### ISSUE TITLE
Confusing note about jumper

### ISSUE THREAD

**Issue by nutttty** [tamanishi/Pinky4#1]
The jumper note starts with "If not," but there's no context. Under what circumstance should the jumper be soldered?

**Comment by cathos** [comment]
I'm confused about it as well. I messaged awhile ago, but did not open an issue.

**Comment by tamanishi** [comment]
Hi.
I'm sorry for my poor English.

I replaced the note.
"If "Jumper" pads are open, it is necessary to solder them."

I hope this has a clearer meaning.

**Comment by nutttty** [comment]
That makes it clear! Thanks!
